### ISSUE TITLE
Nil layoutAnchor

### ISSUE THREAD

**Issue by mergesort** [oarrabi/OALayoutAnchor#1]
```
_myLabel = [[UILabel alloc] init];
_myLabel.translatesAutoresizingMaskIntoConstraints = NO;
[self.contentView addSubview:_titleLabel];

// This ends up being nil because _myLabel is an object, but it's leadingAnchor property is nil.
[_myLabel.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:xPadding],
```

Both `_myLabel` and `self.contentView` are not nil.

My code keeps crashing (being put into an array) because the NSLayoutConstraint that is generated from the `constraintEqualToAnchor` method is nil.

Any ideas?

**Comment by nsomar** [comment]
Hello,
Thanks for the interest in using this library :)

I just noticed that you are you are creating a `_myLabel` but you are then adding `_titleLabel` as a subview. are you sure there is not mistakes in the example you provided?

It will help me immensely if you could provide some compilable source code (maybe a github gist) that I can run. I tried your example and I cannot reproduce it sadly :(.

Can you provide me with a working demo to reproduce the issue?
Also, what iOS version are you using?

Thanks,

**Comment by mergesort** [comment]
@oarrabi Hey, sorry about that, it was a typo (I'm using `_myLabel` everywhere, was trying to make it more general and missed the reference to `_titleLabel`).

While building the demo, I figured out what I was doing wrong. I was trying to create an array of constraints like such

```
- (NSArray *)overlappedTextPositionConstraints
{
    NSArray *constraints = [self titleLabelConstraints:5.0f yPadding:5.0f];
    return constraints;
}

- (NSArray *)underneathTextPositionConstraints
{
    return [self titleLabelConstraints:5.0f yPadding:0.0f];
}

- (NSArray *)titleLabelConstraints:(CGFloat)xPadding yPadding:(CGFloat)yPadding
{
    return @[
                 [_titleLabel.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:xPadding],
                 [_titleLabel.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:xPadding],
                 [_titleLabel.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor constant:yPadding],
                 [_titleLabel.heightAnchor constraintEqualToConstant:30.0f],
             ];
}
```

and then later, based on the position the user sets (to overlap or have the text sit underneath an image), choose between the two like such.

**Comment by mergesort** [comment]
@oarrabi Hey, sorry about that, it was a typo (I'm using `_myLabel` everywhere, was trying to make it more general and missed the reference to `_titleLabel`).

While building the demo, I figured out what I was doing wrong. I was trying to create an array of constraints like such

```
- (NSArray *)overlappedTextPositionConstraints
{
    NSArray *constraints = [self titleLabelConstraints:5.0f yPadding:5.0f];
    return constraints;
}

- (NSArray *)underneathTextPositionConstraints
{
    return [self titleLabelConstraints:5.0f yPadding:0.0f];
}

- (NSArray *)titleLabelConstraints:(CGFloat)xPadding yPadding:(CGFloat)yPadding
{
    return @[
                 [_titleLabel.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:xPadding],
                 [_titleLabel.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:xPadding],
                 [_titleLabel.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor constant:yPadding],
                 [_titleLabel.heightAnchor constraintEqualToConstant:30.0f],
             ];
}
```

and then later, based on the position the user sets (to overlap or have the text sit underneath an image), choose between the two like such.

- (void)setTextPosition:(CellTitleLabelTextPosition)textPosition
{
    NSArray *overlapConstraints = [self overlappedTextPositionConstraints];
    NSArray *underneathConstraints = [self underneathTextPositionConstraints];

    void (^deactivateConstraints) (NSArray *) = ^(NSArray *constraints) {
        [[self.titleLabel.constraints select:^BOOL(NSLayoutConstraint *constraint) {
            return [constraints containsObject:constraint];
        }] each:^(NSLayoutConstraint *constraint) {
            constraint.active = NO;
        }];
    };

    [self.titleLabel.constraints makeObjectsPerformSelector:@selector(setActive:) withObject:@YES];

    if (textPosition == CellTitleLabelTextPositionOverlap)
    {
        deactivateConstraints(underneathConstraints);
        self.titleLabel.textAlignment = NSTextAlignmentLeft;
    }
    else if (textPosition == CellTitleLabelTextPositionUnderneath)
    {
        deactivateConstraints(overlapConstraints);
        self.titleLabel.textAlignment = NSTextAlignmentCenter;
    }
}

**Comment by mergesort** [comment]
@oarrabi Hey, sorry about that, it was a typo (I'm using `_myLabel` everywhere, was trying to make it more general and missed the reference to `_titleLabel`).

While building the demo, I figured out what I was doing wrong, and understood how OALayoutAnchor works better. I'm still trying to figure out this use case though. 

I'm trying to have 2 sets of constraints which I can swap between, when the `textPosition` property changes. I wanted to have them be 2 immutable sets, and just go between the two as such.

```
- (NSArray *)overlappedTextPositionConstraints
{
    NSArray *constraints = [self titleLabelConstraints:5.0f yPadding:5.0f];
    return constraints;
}

- (NSArray *)underneathTextPositionConstraints
{
    return [self titleLabelConstraints:5.0f yPadding:0.0f];
}

- (NSArray *)titleLabelConstraints:(CGFloat)xPadding yPadding:(CGFloat)yPadding
{
    return @[
                 [_titleLabel.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:xPadding],
                 [_titleLabel.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:xPadding],
                 [_titleLabel.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor constant:yPadding],
                 [_titleLabel.heightAnchor constraintEqualToConstant:30.0f],
             ];
}
```

```
// Mutator for textPosition property
- (void)setTextPosition:(CellTitleLabelTextPosition)textPosition
{
    NSArray *overlapConstraints = [self overlappedTextPositionConstraints];
    NSArray *underneathConstraints = [self underneathTextPositionConstraints];

    void (^deactivateConstraints) (NSArray *) = ^(NSArray *constraints) {
        [[self.titleLabel.constraints select:^BOOL(NSLayoutConstraint *constraint) {
            return [constraints containsObject:constraint];
        }] each:^(NSLayoutConstraint *constraint) {
            constraint.active = NO;
        }];
    };

    [self.titleLabel.constraints makeObjectsPerformSelector:@selector(setActive:) withObject:@YES];

    if (textPosition == CellTitleLabelTextPositionOverlap)
    {
        deactivateConstraints(underneathConstraints);
        self.titleLabel.textAlignment = NSTextAlignmentLeft;
    }
    else if (textPosition == CellTitleLabelTextPositionUnderneath)
    {
        deactivateConstraints(overlapConstraints);
        self.titleLabel.textAlignment = NSTextAlignmentCenter;
    }
}
```

Any thoughts on how I could achieve this, or any better suggestion for what might be a more reasonable approach?

Thanks a lot, for the help, and the library!

**Comment by nsomar** [comment]
Hey, I am glad you are enjoying it :)
The code that you posted might work on iOS 8, however wont work on iOS 7, since NSLayoutConstraint does note implement the Active property.
In OALayoutAnchor, I created a category to silence the exception that might happen when calling active https://github.com/oarrabi/OALayoutAnchor/blob/master/Pod/Classes/NSLayoutConstraint%2BSuppressActive.m. This might cause strange misunderstanding.

If I had your same issue, I would iterate over the constraint and only change their constant value.
So instead of activating and deactivating, I would store the constraint constant values and switch them based on what set of constants I want. and then iterate and do `theconstraint.constant = thevalue;`
This also helps in improving the performance since the constraints are reused.

Will this work for you case?

**Comment by mergesort** [comment]
I'm on iOS 8, not supporting 7, so I get the limitation, but don't mind it. :) 

Yes, that would work in this case! But I have another case where there are 2 layouts for a view, which are not particularly similar (and wouldn't constrain the views in the same way necessarily). The other issue with the method of changing the constants (while more performant for sure) is that now I have to create properties (global state) to hold onto the constraints I'd like to change, instead of swapping in one set for another.
